services:
    web-app:
        build:
            context: .
        ports:
            - "8080:8080"
        volumes:
            - ./service:/service
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASS=dbpass

        command: >
            sh -c "python manage.py runserver 0.0.0.0:8080"

        depends_on:
            - database

    database:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=dbname
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpass

    redis:
        image: redis:alpine
        hostname: redis

    worker:
        build:
            context: .
        hostname: worker
        entrypoint: celery
        command: -A celery_app.app worker --loglevel=info
        volumes:
            - ./service:/service
        links:
            - redis
        depends_on:
            - redis
            - database
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASS=dbpass

    worker2:
        build:
            context: .
        hostname: worker2
        entrypoint: celery
        command: -A celery_app.app worker --loglevel=info
        volumes:
            - ./service:/service
        links:
            - redis
        depends_on:
            - redis
            - database
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASS=dbpass

    flower:
        build:
            context: .
        hostname: flower
        entrypoint: celery
        command: -A celery_app.app flower
        volumes:
            - ./service:/service
        links:
            - redis
        depends_on:
            - redis
        ports:
            - "5555:5555"
