services:
    web-app:
        build:
            context: .
        ports:
            - "8080:8080"
        volumes:
            - ./service:/service

        command: >
            sh -c "python manage.py runserver 0.0.0.0:8080"
