services:
    web-app:
        build:
            context: .
        ports:
            - "8080:8080"
        volumes:
            - ./service:/service
        environment:
            - DB_HOST=database
            - DB_NAME=dbname
            - DB_USER=dbuser
            - DB_PASS=dbpass

        command: >
            sh -c "python manage.py runserver 0.0.0.0:8080"

        depends_on:
            - database

    database:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=dbname
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpass
