# Generated by Django 5.0.4 on 2024-05-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_subscription_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
