# Generated by Django 5.0.4 on 2024-05-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_subscription_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
