# Generated by Django 5.0.4 on 2024-05-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
